// let now = new Date()
// // alert(now)
// let st = new Date(0)
// alert(st)
// // alert(now)
// let bt = new Date(12 * 30 * 24 * 3600 * 1000)
// alert(bt)
// let now = new Date()
// alert(now)
// console.log(now.getHours())

let now = new Date()
console.log(now.getFullYear())
now.setFullYear(now.getFullYear()+3)
console.log(now)